CPPFLAGS=-g -fpic
OUTDIR=bin/
SRCDIR=src/

all: 2D_ARAY 2DArray BaseDerived ClassMembers ConstPtr ExampleSampleC ExampleSample IntArrayLength Isomorphic LinkedList MergeArraysAO StringPermutations StringClass BitwiseOperators OpenWebURL MallocExample BST

clean:
	rm ${OUTDIR}*.o

StringClass:
	g++ $(CPPFLAGS) ${SRCDIR}StringClass.cpp -o ${OUTDIR}StringClass.o

BitwiseOperators:
	g++ $(CPPFLAGS) ${SRCDIR}BitwiseOperators.cpp -o ${OUTDIR}BitwiseOperators.o

OpenWebURL:
	g++ $(CPPFLAGS) ${SRCDIR}OpenWebURL.cpp -o ${OUTDIR}OpenWebURL.o

2D_ARAY:
	g++ $(CPPFLAGS) ${SRCDIR}2D_ARAY.cpp -o ${OUTDIR}2D_ARAY.o

2DArray:
	g++ $(CPPFLAGS) ${SRCDIR}2DArray.cpp -o ${OUTDIR}2DArray.o

BaseDerived:
	g++ $(CPPFLAGS) ${SRCDIR}BaseDerived.cpp -o ${OUTDIR}BaseDerived.o

BST:
	g++ $(CPPFLAGS) ${SRCDIR}BST.cpp -o ${OUTDIR}BST.o

ClassMembers:
	g++ $(CPPFLAGS) ${SRCDIR}ClassMembers.cpp -o ${OUTDIR}ClassMembers.o

ConstPtr:
	g++ $(CPPFLAGS) ${SRCDIR}ConstPtr.cpp -o ${OUTDIR}ConstPtr.o

ExampleSampleC:
	g++ $(CPPFLAGS) ${SRCDIR}ExampleSample.c -o ${OUTDIR}ExampleSample.o

ExampleSample:
	g++ $(CPPFLAGS) ${SRCDIR}ExampleSample.cpp -o ${OUTDIR}ExampleSample.o

IntArrayLength:
	g++ $(CPPFLAGS) ${SRCDIR}IntArrayLength.cpp -o ${OUTDIR}IntArrayLength.o

Isomorphic:
	g++ $(CPPFLAGS) ${SRCDIR}Isomorphic.cpp -o ${OUTDIR}Isomorphic.o

JunkCode:
	g++ $(CPPFLAGS) ${SRCDIR}JunkCode.cpp -o ${OUTDIR}JunkCode.o

LinkedList:
	g++ $(CPPFLAGS) ${SRCDIR}LinkedList.cpp -o ${OUTDIR}LinkedList.o

MergeArraysAO:
	g++ $(CPPFLAGS) ${SRCDIR}MergeArraysAO.cpp -o ${OUTDIR}MergeArraysAO.o

StringPermutations:
	g++ $(CPPFLAGS) ${SRCDIR}StringPermutations.cpp -o ${OUTDIR}StringPermutations.o

MallocExample:
	cc ${SRCDIR}MallocExample.c -o ${OUTDIR}MallocExample.o

