all:
	g++ -pthread ConditioVariablesT.cpp -o ConditioVariablesT.o
	g++ -pthread DetachedThread.cpp -o DetachedThread.o
	g++ -pthread manyThreads.cpp -o manyThreads.o
	g++ -pthread mutexThreads.cpp -o mutexThreads.o
	g++ -pthread pthreadExample.cpp -o pthreadExample.o
	g++ -pthread valueThreads.cpp -o valueThreads.o

IntegerPthread:
	g++ -pthread IntegerPthread.cpp -o IntegerPthread.o

clean:
	rm -f *.o

