# -----------------------------------------------------------------------------
# Makefile to build TelephoneDirectory code
# -----------------------------------------------------------------------------

all:
	g++ TelephoneDirectory.cpp -o TelephoneDirectory.o

clean:
	rm -f TelephoneDirectory.o

